# Generated by Django 6.0.6 on 2026-06-30 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('organism', models.CharField(max_length=150)),
                ('crop_stage', models.CharField(max_length=150)),
                ('disease_type', models.CharField(choices=[('fungal', 'Fungal'), ('bacterial', 'Bacterial'), ('viral', 'Viral'), ('phytoplasma', 'Phytoplasma'), ('pest', 'Pest')], max_length=20)),
                ('irrigation_requirement_l', models.CharField(blank=True, max_length=30)),
                ('actual_irrigation_given', models.CharField(blank=True, max_length=30)),
                ('rainfall_mm_week', models.CharField(max_length=30)),
                ('vapour_pressure_kpa', models.CharField(max_length=30)),
                ('vpd_kpa', models.CharField(max_length=30)),
                ('relative_humidity_pct', models.CharField(max_length=30)),
                ('avg_temp_c', models.CharField(max_length=30)),
                ('leaf_wetness_hrs', models.CharField(max_length=30)),
                ('gdd_range', models.CharField(max_length=30)),
                ('risk_score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sr_no'],
            },
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(default='Dhakpade Farm', max_length=120)),
                ('farmer_name', models.CharField(default='Abhinav R. Dhakpade', max_length=120)),
                ('village', models.CharField(default='Baramati, Pune', max_length=120)),
                ('latitude', models.FloatField(default=18.1514)),
                ('longitude', models.FloatField(default=74.5815)),
                ('variety', models.CharField(default='Co 86032', max_length=60)),
                ('planting_date', models.DateField()),
                ('soil_type', models.CharField(default='Black Cotton', max_length=60)),
                ('irrigation_method', models.CharField(default='Drip', max_length=60)),
                ('area_hectares', models.FloatField(default=2.4)),
                ('base_temp_c', models.FloatField(default=18.0)),
                ('expected_harvest', models.CharField(default='Dec 2025', max_length=60)),
                ('expected_yield_t_ha', models.CharField(default='78–85', max_length=30)),
                ('revenue_estimate', models.CharField(default='₹3.5–3.8 L', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField(unique=True)),
                ('soil_type', models.CharField(max_length=60)),
                ('crop_stage', models.CharField(max_length=60)),
                ('moisture_pct', models.CharField(max_length=30)),
                ('rainfall_mm_week', models.CharField(max_length=30)),
                ('temp_c', models.CharField(max_length=30)),
                ('relative_humidity_pct', models.CharField(max_length=30)),
                ('vpd_kpa', models.CharField(max_length=30)),
                ('etc_mm_day', models.CharField(max_length=30)),
                ('requirement_l_plant', models.CharField(max_length=30)),
                ('decision', models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('remark', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['sr_no'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(choices=[('fungal', 'Fungal'), ('bacterial', 'Bacterial'), ('viral', 'Viral'), ('phytoplasma', 'Phytoplasma'), ('pest', 'Pest')], max_length=20, unique=True)),
                ('biological', models.TextField()),
                ('chemical', models.TextField()),
                ('timing', models.TextField()),
                ('safety', models.TextField()),
                ('recovery', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CropGrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=60)),
                ('gdd_threshold', models.FloatField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_stages', to='advisory.farmprofile')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('ok', 'OK')], max_length=10)),
                ('icon', models.CharField(default='🔔', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='advisory.farmprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisoryTimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_label', models.CharField(max_length=60)),
                ('dot_state', models.CharField(choices=[('done', 'Done'), ('today', 'Today'), ('upcoming', 'Upcoming')], max_length=10)),
                ('action', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='advisory.farmprofile')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_max_c', models.FloatField()),
                ('temp_min_c', models.FloatField()),
                ('humidity_pct', models.FloatField()),
                ('rainfall_mm', models.FloatField()),
                ('et0_mm', models.FloatField()),
                ('vpd_kpa', models.FloatField()),
                ('solar_mj_m2', models.FloatField()),
                ('wind_kmh', models.FloatField()),
                ('gdd_daily', models.FloatField()),
                ('gdd_cumulative', models.FloatField()),
                ('weather_icon', models.CharField(default='⛅', max_length=10)),
                ('is_forecast', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_readings', to='advisory.farmprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('farm', 'date')},
            },
        ),
    ]
