# Generated by Django 6.0.6 on 2026-06-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='rule_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual / Seeded'), ('weather_rule', 'Auto-generated from weather forecast')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='condition_text',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='data_source',
            field=models.CharField(default='seed', max_length=20),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='precipitation_probability_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='soil_temp_0cm_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='sunrise',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='sunset',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='uv_index_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='weather_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='wind_direction_deg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='wind_gusts_kmh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
