# Generated by Django 6.0.6 on 2026-07-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0002_alert_rule_key_alert_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmprofile',
            name='crop_name',
            field=models.CharField(default='Sugarcane', max_length=80),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='irrigation_method',
            field=models.CharField(choices=[('Drip', 'Drip'), ('Sprinkler', 'Sprinkler'), ('Flood', 'Flood'), ('Furrow', 'Furrow'), ('Rainfed', 'Rainfed')], default='Drip', max_length=60),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='soil_type',
            field=models.CharField(choices=[('Black Cotton', 'Black Cotton'), ('Loamy', 'Loamy'), ('Sandy', 'Sandy'), ('Clay', 'Clay'), ('Red Soil', 'Red Soil'), ('Laterite', 'Laterite'), ('Alluvial', 'Alluvial')], default='Black Cotton', max_length=60),
        ),
    ]
