# Generated by Django 6.0.6 on 2026-07-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0003_farmprofile_crop_name_farmprofile_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='sync_weather', max_length=80)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled (hourly)'), ('manual', 'Manual'), ('startup', 'Startup catch-up')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failure', 'Failure')], default='failure', max_length=10)),
                ('farms_processed', models.PositiveIntegerField(default=0)),
                ('records_fetched', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('duplicates_removed', models.PositiveIntegerField(default=0)),
                ('retry_attempts', models.PositiveIntegerField(default=0)),
                ('nasa_power_status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed')], default='ok', max_length=10)),
                ('open_meteo_status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed')], default='ok', max_length=10)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
