# Generated by Django 6.0.6 on 2026-07-20 06:01

import django.db.models.deletion
from django.db import migrations, models


def copy_weather_reading_data(apps, schema_editor):
    """
    Preserves every existing WeatherReading row across the split: rows with
    is_forecast=False go to ActualWeatherReading, is_forecast=True rows go to
    ForecastWeatherReading (backfilled with default confidence_score/
    prediction_model since the old table never tracked those). Runs before
    DeleteModel below removes the old table, so nothing collected by the
    hourly scheduler or a manual sync is lost.
    """
    WeatherReading = apps.get_model("advisory", "WeatherReading")
    ActualWeatherReading = apps.get_model("advisory", "ActualWeatherReading")
    ForecastWeatherReading = apps.get_model("advisory", "ForecastWeatherReading")

    shared_fields = [
        "farm_id", "date", "temp_max_c", "temp_min_c", "humidity_pct", "rainfall_mm",
        "et0_mm", "vpd_kpa", "solar_mj_m2", "wind_kmh", "gdd_daily", "gdd_cumulative",
        "weather_icon", "wind_direction_deg", "wind_gusts_kmh", "uv_index_max",
        "precipitation_probability_pct", "sunrise", "sunset", "soil_temp_0cm_c",
        "weather_code", "condition_text", "data_source", "fetched_at",
    ]

    actual_rows = []
    forecast_rows = []
    for row in WeatherReading.objects.all().iterator():
        values = {field: getattr(row, field) for field in shared_fields}
        if row.is_forecast:
            forecast_rows.append(ForecastWeatherReading(**values))
        else:
            actual_rows.append(ActualWeatherReading(**values))

    if actual_rows:
        ActualWeatherReading.objects.bulk_create(actual_rows, ignore_conflicts=True)
    if forecast_rows:
        ForecastWeatherReading.objects.bulk_create(forecast_rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    # Not reversible: WeatherReading no longer exists by the time this would
    # run, and the split loses no information that would need restoring here.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0004_schedulerlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualWeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_max_c', models.FloatField()),
                ('temp_min_c', models.FloatField()),
                ('humidity_pct', models.FloatField()),
                ('rainfall_mm', models.FloatField()),
                ('et0_mm', models.FloatField()),
                ('vpd_kpa', models.FloatField()),
                ('solar_mj_m2', models.FloatField()),
                ('wind_kmh', models.FloatField()),
                ('gdd_daily', models.FloatField()),
                ('gdd_cumulative', models.FloatField()),
                ('weather_icon', models.CharField(default='⛅', max_length=10)),
                ('wind_direction_deg', models.FloatField(blank=True, null=True)),
                ('wind_gusts_kmh', models.FloatField(blank=True, null=True)),
                ('uv_index_max', models.FloatField(blank=True, null=True)),
                ('precipitation_probability_pct', models.FloatField(blank=True, null=True)),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('sunset', models.TimeField(blank=True, null=True)),
                ('soil_temp_0cm_c', models.FloatField(blank=True, null=True)),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('condition_text', models.CharField(blank=True, max_length=60)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.CharField(default='nasa_power', max_length=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_weather_readings', to='advisory.farmprofile')),
            ],
            options={
                'verbose_name': 'Actual weather reading',
                'ordering': ['date'],
                'unique_together': {('farm', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ForecastWeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_max_c', models.FloatField()),
                ('temp_min_c', models.FloatField()),
                ('humidity_pct', models.FloatField()),
                ('rainfall_mm', models.FloatField()),
                ('et0_mm', models.FloatField()),
                ('vpd_kpa', models.FloatField()),
                ('solar_mj_m2', models.FloatField()),
                ('wind_kmh', models.FloatField()),
                ('gdd_daily', models.FloatField()),
                ('gdd_cumulative', models.FloatField()),
                ('weather_icon', models.CharField(default='⛅', max_length=10)),
                ('wind_direction_deg', models.FloatField(blank=True, null=True)),
                ('wind_gusts_kmh', models.FloatField(blank=True, null=True)),
                ('uv_index_max', models.FloatField(blank=True, null=True)),
                ('precipitation_probability_pct', models.FloatField(blank=True, null=True)),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('sunset', models.TimeField(blank=True, null=True)),
                ('soil_temp_0cm_c', models.FloatField(blank=True, null=True)),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('condition_text', models.CharField(blank=True, max_length=60)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.CharField(default='open_meteo', max_length=20)),
                ('confidence_score', models.FloatField(default=0.9, help_text='0-1 confidence, decaying with lead time from today (forecast skill degrades with horizon).')),
                ('prediction_model', models.CharField(default='Open-Meteo (ICON/GFS blend)', max_length=80)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_weather_readings', to='advisory.farmprofile')),
            ],
            options={
                'verbose_name': 'Forecast weather reading',
                'ordering': ['date'],
                'unique_together': {('farm', 'date')},
            },
        ),
        migrations.RunPython(copy_weather_reading_data, noop_reverse),
        migrations.DeleteModel(
            name='WeatherReading',
        ),
    ]
