# Generated by Django 6.0.6 on 2026-07-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0005_split_actual_forecast_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmprofile',
            name='boundary_geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='boundary_source_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
