# Generated by Django 6.0.6 on 2026-08-01 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0006_farmprofile_boundary_geojson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmprofile',
            name='pump_discharge_l_s',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='pump_hp',
            field=models.FloatField(default=5.0),
        ),
        migrations.CreateModel(
            name='IrrigationRequirementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('crop_stage', models.CharField(max_length=60)),
                ('kc', models.FloatField()),
                ('et0_mm_day', models.FloatField()),
                ('etc_mm_day', models.FloatField()),
                ('effective_rainfall_mm_day', models.FloatField(default=0.0)),
                ('net_requirement_mm_day', models.FloatField()),
                ('field_area_m2', models.FloatField()),
                ('water_required_l_day', models.FloatField()),
                ('pump_hp', models.FloatField(blank=True, null=True)),
                ('pump_discharge_l_s', models.FloatField()),
                ('pump_capacity_l_hr', models.FloatField()),
                ('irrigation_time_hr', models.FloatField()),
                ('irrigation_time_label', models.CharField(max_length=30)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_logs', to='advisory.farmprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('farm', 'date')},
            },
        ),
    ]
