# Generated by Django 6.0.6 on 2026-08-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0007_farmprofile_pump_discharge_l_s_farmprofile_pump_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmprofile',
            name='elevation_m',
            field=models.FloatField(default=560.0),
        ),
    ]
