"""
advisory/export/pdf_report.py

Generates a one-page "Today's Advisory" PDF for a farm: health score, weather
snapshot, top disease risks, irrigation recommendation, active alerts, and the
advisory timeline. Built with ReportLab (pure Python, no headless browser or
external binary dependency) so it works in any deployment environment without
extra system packages.
"""

from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

GREEN_DEEP = colors.HexColor("#1a4731")
GREEN_MID = colors.HexColor("#2d7a4f")
GREEN_PALE = colors.HexColor("#c8f0da")
RED = colors.HexColor("#d63230")
AMBER = colors.HexColor("#e07b00")
SKY = colors.HexColor("#1e8bc3")
TEXT_MUTED = colors.HexColor("#4a6358")


def _risk_color(score):
    if score >= 70:
        return colors.HexColor("#b80000")
    if score >= 50:
        return colors.HexColor("#b85000")
    if score >= 30:
        return colors.HexColor("#8a6200")
    return colors.HexColor("#1a7a3e")


def _styles():
    base = getSampleStyleSheet()
    base.add(ParagraphStyle("ReportTitle", parent=base["Title"], fontSize=20, textColor=GREEN_DEEP, spaceAfter=2))
    base.add(ParagraphStyle("ReportSub", parent=base["Normal"], fontSize=10, textColor=TEXT_MUTED, spaceAfter=14))
    base.add(ParagraphStyle("SectionHead", parent=base["Heading2"], fontSize=12, textColor=GREEN_DEEP, spaceBefore=14, spaceAfter=6))
    base.add(ParagraphStyle("BodySmall", parent=base["Normal"], fontSize=9, textColor=colors.HexColor("#2a2a2a"), leading=13))
    base.add(ParagraphStyle("Footer", parent=base["Normal"], fontSize=7.5, textColor=TEXT_MUTED, alignment=TA_CENTER))
    return base


def build_advisory_pdf(payload: dict) -> bytes:
    """
    payload mirrors the shape of /api/dashboard/: farm, today_weather, top_diseases,
    alerts, timeline, irrigation_snapshot, health_score, current_stage, current_gdd.
    """
    buf = io.BytesIO()
    styles = _styles()

    doc = BaseDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=16 * mm, leftMargin=16 * mm, rightMargin=16 * mm)
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="main")

    def footer(canvas, doc_):
        canvas.saveState()
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(TEXT_MUTED)
        canvas.drawCentredString(
            A4[0] / 2, 10 * mm,
            f"Generated by AgriAura · {datetime.now().strftime('%d %b %Y, %I:%M %p')} · "
            "Deterministic agronomy + ML second opinion + live NASA POWER / Open-Meteo data",
        )
        canvas.restoreState()

    doc.addPageTemplates([PageTemplate(id="report", frames=[frame], onPage=footer)])

    story = []
    farm = payload.get("farm", {})
    weather = payload.get("today_weather") or {}
    diseases = payload.get("top_diseases", [])[:6]
    alerts = payload.get("alerts", [])[:5]
    timeline = payload.get("timeline", [])
    irrigation = payload.get("irrigation_snapshot")

    # --- Header ---
    story.append(Paragraph("AgriAura — Today's Field Advisory", styles["ReportTitle"]))
    story.append(
        Paragraph(
            f"{farm.get('farm_name', 'Farm')} · {farm.get('village', '')} · "
            f"{farm.get('variety', '')} · {payload.get('current_stage', '')} stage · "
            f"{datetime.now().strftime('%A, %d %B %Y')}",
            styles["ReportSub"],
        )
    )

    # --- Top summary table: health score / GDD / stage ---
    health_score = payload.get("health_score", "—")
    summary_data = [
        ["Crop Health Score", "GDD Accumulated", "Current Stage", "Temp / Humidity Today"],
        [
            f"{health_score} / 100",
            f"{round(payload.get('current_gdd', 0)):,}",
            payload.get("current_stage", "—"),
            f"{weather.get('temp_max_c', '—')}°C / {weather.get('humidity_pct', '—')}%",
        ],
    ]
    summary_table = Table(summary_data, colWidths=[doc.width / 4] * 4)
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), GREEN_DEEP),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, 0), 8),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("BACKGROUND", (0, 1), (-1, 1), GREEN_PALE),
                ("FONTSIZE", (0, 1), (-1, 1), 13),
                ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
                ("TEXTCOLOR", (0, 1), (-1, 1), GREEN_DEEP),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.white),
            ]
        )
    )
    story.append(summary_table)

    # --- Disease risk section ---
    story.append(Paragraph("Top Disease & Pest Risks", styles["SectionHead"]))
    if diseases:
        rows = [["Disease", "Risk", "Crop Stage", "Notes"]]
        for d in diseases:
            ml_note = ""
            if d.get("ml_risk_pct") is not None:
                ml_note = f"ML: {d['ml_risk_pct']}%"
            rows.append([d["name"], f"{d['risk_score']}% ({d['risk_label']})", d.get("crop_stage", "")[:40], ml_note])
        disease_table = Table(rows, colWidths=[doc.width * 0.28, doc.width * 0.22, doc.width * 0.35, doc.width * 0.15])
        style_cmds = [
            ("BACKGROUND", (0, 0), (-1, 0), GREEN_MID),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d8e8df")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]
        for i, d in enumerate(diseases, start=1):
            style_cmds.append(("TEXTCOLOR", (1, i), (1, i), _risk_color(d["risk_score"])))
            style_cmds.append(("FONTNAME", (1, i), (1, i), "Helvetica-Bold"))
            if i % 2 == 0:
                style_cmds.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor("#f7faf8")))
        disease_table.setStyle(TableStyle(style_cmds))
        story.append(disease_table)
    else:
        story.append(Paragraph("No disease data available.", styles["BodySmall"]))

    # --- Irrigation section ---
    story.append(Paragraph("Irrigation Recommendation", styles["SectionHead"]))
    if irrigation:
        irr_text = (
            f"<b>{irrigation.get('soil_type', '')} soil, {irrigation.get('crop_stage', '')} stage</b> — "
            f"Decision: <b>{irrigation.get('decision', '—')}</b>. "
            f"Requirement: {irrigation.get('requirement_l_plant', '—')} L/plant. "
            f"{irrigation.get('remark', '')}"
        )
        story.append(Paragraph(irr_text, styles["BodySmall"]))
    else:
        story.append(Paragraph("No irrigation snapshot available for this farm's soil type.", styles["BodySmall"]))

    # --- Alerts section ---
    story.append(Paragraph("Active Alerts", styles["SectionHead"]))
    if alerts:
        for a in alerts:
            tag = " [LIVE]" if a.get("source") == "weather_rule" else ""
            story.append(Paragraph(f"<b>{a['icon']} {a['title']}{tag}</b> — {a['description']}", styles["BodySmall"]))
            story.append(Spacer(1, 3))
    else:
        story.append(Paragraph("No active alerts.", styles["BodySmall"]))

    # --- Timeline section ---
    story.append(Paragraph("Advisory Timeline — What To Do Next", styles["SectionHead"]))
    if timeline:
        rows = [["When", "Action", "Note"]]
        for t in timeline:
            rows.append([t["when_label"], t["action"], t["note"]])
        tl_table = Table(rows, colWidths=[doc.width * 0.18, doc.width * 0.32, doc.width * 0.5])
        tl_style = [
            ("BACKGROUND", (0, 0), (-1, 0), GREEN_MID),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d8e8df")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]
        for i in range(1, len(rows)):
            if i % 2 == 0:
                tl_style.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor("#f7faf8")))
        tl_table.setStyle(TableStyle(tl_style))
        story.append(tl_table)
    else:
        story.append(Paragraph("No timeline items.", styles["BodySmall"]))

    doc.build(story)
    return buf.getvalue()
